In [1]:
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
class0_len = 1000
x0 = np.random.normal((0,1,2),(1,2,2),(class0_len,3))
y0 = [0]*class0_len

class1_len = 2000
x1 = np.random.normal((1,1,-1),(3,1,1),(class1_len,3))
y1 = [1]*class1_len

In [48]:
print(x1)
y1

[[ 0.07208868  0.97324685 -0.26105573]
 [-0.31593448  1.19291683 -1.92768746]
 [ 7.19626424  1.36709348 -1.55066682]
 ...
 [ 1.81563953  2.12827367 -0.72979374]
 [ 5.95709503  0.47988246 -0.6465134 ]
 [ 1.2240602   1.27534275 -2.34941211]]


[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [11]:
X = np.concatenate((x0,x1))
y = y0 +y1

In [12]:
X_train , X_val , y_train, y_val = train_test_split(X,y,random_state = 24)

In [13]:
clf = LogisticRegression()
clf.fit(X_train,y_train)
print(clf.score(X_train,y_train))
print(clf.score(X_val,y_val))

0.8924444444444445
0.8866666666666667


In [39]:
y_val

[0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,


In [31]:
def perf_measure(y_actual,y_hat):
    
    tp = 0
    tn = 0
    fp = 0
    fn = 0
    
    for i in range(len(y_hat)):
        if y_actual[i]==y_hat[i] and y_hat[i]==1:
            tp = tp + 1
        if y_actual[i]==y_hat[i] and y_hat[i]== 0:
            tn = tn + 1
        if y_actual[i]!=y_hat[i] and y_hat[i]==1:
            fp = fp + 1
        if y_actual[i]!=y_hat[i] and y_hat[i]==0:
            fn = fn + 1
        
    
    return (tp,fp,tn,fn)

In [36]:
tp,fp,tn,fn = perf_measure(y_val, clf.predict(X_val))

In [86]:
def all_scores(tp,fp,tn,fn):
    precision = tp/(tp+fp)
    recall = tp/(tp+fn)
    specificity = tn/(tn+fp)
    npv = tn/(tn+fn)
    
    f1_score = 2*precision*recall/(precision+recall)
    accuracy = (tp+tn)/(tp+fp+tn+fn)
       
    print("precision:",precision)
    print("recall:",recall)
    print("specificity:",specificity)
    print("npv:",npv)
    
    print("f1_score",f1_score)
    print("accuracy:",accuracy)

In [87]:
all_scores(620,1,50,150)

accuracy: 0.8160779537149817
precision: 0.998389694041868
recall: 0.8051948051948052
f1_score 0.8914450035945363
spec: 0.9803921568627451
npv: 0.25
